export const STRINGS = {
  bn: {
    appName: 'নিডল',
    appSubtitle: 'KNEEDLE',
    appTagline: 'আপনার হাঁটুর যত্নে, প্রতিদিন',
    startBtn: 'শুরু করুন →',
    freeNote: 'বিনামূল্যে · ইন্টারনেট লাগবে না',
    languageLabel: 'ভাষা:',
    profileTitle: 'আপনার পরিচয়',
    profileSubtitle: 'একবার সেট করুন',
    namePlaceholder: 'আপনার নাম লিখুন',
    agePlaceholder: 'বয়স',
    whichKnee: 'কোন হাঁটুতে ব্যথা?',
    kneeLeft: 'বাম',
    kneeRight: 'ডান',
    kneeBoth: 'দুটোই',
    painLevel: 'ব্যথার মাত্রা',
    painLow: 'কম',
    painMid: 'মাঝারি',
    painHigh: 'বেশি',
    saveBtn: 'সংরক্ষণ করুন →',
    greeting: 'নমস্কার 🙏',
    todayPain: 'আজ ব্যথা কেমন?',
    recordBtn: 'হাঁটা রেকর্ড করুন',
    recordSub: '১৫ সেকেন্ড · AI বিশ্লেষণ',
    historyBtn: 'আগের রিপোর্ট দেখুন',
    historySub: 'সেশন সম্পন্ন',
    weekProgress: 'এই সপ্তাহ',
    daysLabel: 'দিন ✓',
    recordTitle: 'হাঁটা রেকর্ড করুন',
    recordSubtitle: '১৫ সেকেন্ড যথেষ্ট',
    step1: 'ফোন দেওয়ালে রাখুন, মাটি থেকে ৩ ফুট উঁচুতে',
    step2: '৩ মিটার দূরে দাঁড়িয়ে লাল বোতাম চাপুন',
    step3: 'স্বাভাবিকভাবে ফোনের দিকে হাঁটুন',
    startRecord: '● রেকর্ড শুরু করুন',
    stopRecord: '⏹ থামুন',
    cancelBtn: 'বাতিল',
    analyseBtn: 'বিশ্লেষণ করুন →',
    analysisStep1: 'পদক্ষেপের ছন্দ বিশ্লেষণ',
    analysisStep2: 'হাঁটুর কোণ পরিমাপ হচ্ছে...',
    analysisStep3: 'ভারসাম্য মূল্যায়ন',
    analysisStep4: 'রিপোর্ট তৈরি',
    rightKneeLabel: 'ডান হাঁটু',
    leftKneeLabel: 'বাম হাঁটু',
    resultsTitle: 'আজকের রিপোর্ট',
    observationTag: '🔍 যা দেখা গেল',
    fixTag: '✏️ আজ একটাই কাজ',
    exerciseTag: '🧘 আজকের ব্যায়াম',
    speakBtn: '🔊 বাংলায় শুনুন',
    saveReport: 'রিপোর্ট সংরক্ষণ করুন',
    homeBtn: 'হোমে ফিরুন',
    historyTitle: 'অগ্রগতি',
    painTrend: 'ব্যথার মাত্রা · গত ৭ দিন',
    improving: 'উন্নতি হচ্ছে',
    same: 'একই রকম',
    worse: 'খারাপ হচ্ছে',
    firstSession: 'প্রথম দিন',
    baselineSet: 'বেসলাইন তৈরি',
    noHistory: 'এখনো কোনো রিপোর্ট নেই',
    noHistorySub: 'প্রথম হাঁটা রেকর্ড করুন',
    days: ['সোম','মঙ্গল','বুধ','বৃহ','শুক্র','শনি','আজ'],
    diSuffix: ' দি',
    symmetryScore: 'সামঞ্জস্য স্কোর',
    session: 'সেশন',
  },

  hi: {
    appName: 'नीडल',
    appSubtitle: 'KNEEDLE',
    appTagline: 'आपके घुटनों की देखभाल, हर दिन',
    startBtn: 'शुरू करें →',
    freeNote: 'मुफ़्त · इंटरनेट की ज़रूरत नहीं',
    languageLabel: 'भाषा:',
    profileTitle: 'आपका परिचय',
    profileSubtitle: 'एक बार सेट करें',
    namePlaceholder: 'अपना नाम लिखें',
    agePlaceholder: 'उम्र',
    whichKnee: 'कौन सा घुटना दर्द करता है?',
    kneeLeft: 'बायाँ',
    kneeRight: 'दायाँ',
    kneeBoth: 'दोनों',
    painLevel: 'दर्द का स्तर',
    painLow: 'कम',
    painMid: 'मध्यम',
    painHigh: 'ज़्यादा',
    saveBtn: 'सहेजें →',
    greeting: 'नमस्ते 🙏',
    todayPain: 'आज दर्द कैसा है?',
    recordBtn: 'चलना रिकॉर्ड करें',
    recordSub: '१५ सेकंड · AI विश्लेषण',
    historyBtn: 'पुरानी रिपोर्ट देखें',
    historySub: 'सत्र पूरे हुए',
    weekProgress: 'इस हफ़्ते',
    daysLabel: 'दिन ✓',
    recordTitle: 'चलना रिकॉर्ड करें',
    recordSubtitle: '१५ सेकंड काफ़ी है',
    step1: 'फ़ोन को दीवार से लगाएं, ३ फ़ीट ऊँचाई पर',
    step2: '३ मीटर दूर खड़े होकर लाल बटन दबाएं',
    step3: 'स्वाभाविक रूप से फ़ोन की तरफ़ चलें',
    startRecord: '● रिकॉर्ड शुरू करें',
    stopRecord: '⏹ रुकें',
    cancelBtn: 'रद्द करें',
    analyseBtn: 'विश्लेषण करें →',
    analysisStep1: 'क़दमों की लय का विश्लेषण',
    analysisStep2: 'घुटने का कोण माप रहे हैं...',
    analysisStep3: 'संतुलन मूल्यांकन',
    analysisStep4: 'रिपोर्ट तैयार हो रही है',
    rightKneeLabel: 'दायाँ घुटना',
    leftKneeLabel: 'बायाँ घुटना',
    resultsTitle: 'आज की रिपोर्ट',
    observationTag: '🔍 जो दिखा',
    fixTag: '✏️ आज बस एक काम',
    exerciseTag: '🧘 आज का व्यायाम',
    speakBtn: '🔊 हिंदी में सुनें',
    saveReport: 'रिपोर्ट सहेजें',
    homeBtn: 'होम पर जाएं',
    historyTitle: 'प्रगति',
    painTrend: 'दर्द का स्तर · पिछले ७ दिन',
    improving: 'सुधार हो रहा है',
    same: 'वही स्थिति',
    worse: 'बिगड़ रहा है',
    firstSession: 'पहला दिन',
    baselineSet: 'बेसलाइन तैयार',
    noHistory: 'अभी कोई रिपोर्ट नहीं',
    noHistorySub: 'पहला चलना रिकॉर्ड करें',
    days: ['सोम','मंगल','बुध','गुरु','शुक्र','शनि','आज'],
    diSuffix: ' जी',
    symmetryScore: 'समरूपता स्कोर',
    session: 'सत्र',
  },

  en: {
    appName: 'Kneedle',
    appSubtitle: 'KNEEDLE',
    appTagline: 'Your personal knee physiotherapist',
    startBtn: 'Get Started →',
    freeNote: 'Free · No internet needed',
    languageLabel: 'Language:',
    profileTitle: 'Your Profile',
    profileSubtitle: 'Set once, remembered always',
    namePlaceholder: 'Your name',
    agePlaceholder: 'Age',
    whichKnee: 'Which knee hurts?',
    kneeLeft: 'Left',
    kneeRight: 'Right',
    kneeBoth: 'Both',
    painLevel: 'Pain level',
    painLow: 'Low',
    painMid: 'Medium',
    painHigh: 'High',
    saveBtn: 'Save →',
    greeting: 'Hello 🙏',
    todayPain: 'How is the pain today?',
    recordBtn: 'Record your walk',
    recordSub: '15 seconds · AI analysis',
    historyBtn: 'View past reports',
    historySub: 'sessions done',
    weekProgress: 'This week',
    daysLabel: 'days ✓',
    recordTitle: 'Record your walk',
    recordSubtitle: '15 seconds is enough',
    step1: 'Lean phone against wall, 3 feet off ground',
    step2: 'Stand 3 metres away, press red button',
    step3: 'Walk naturally toward the phone',
    startRecord: '● Start Recording',
    stopRecord: '⏹ Stop',
    cancelBtn: 'Cancel',
    analyseBtn: 'Analyse →',
    analysisStep1: 'Analysing step rhythm',
    analysisStep2: 'Measuring knee angle...',
    analysisStep3: 'Balance assessment',
    analysisStep4: 'Generating report',
    rightKneeLabel: 'Right knee',
    leftKneeLabel: 'Left knee',
    resultsTitle: "Today's Report",
    observationTag: '🔍 What we observed',
    fixTag: '✏️ One thing to do today',
    exerciseTag: "🧘 Today's exercises",
    speakBtn: '🔊 Read aloud',
    saveReport: 'Save report',
    homeBtn: 'Back to home',
    historyTitle: 'Progress',
    painTrend: 'Pain level · Last 7 days',
    improving: 'Improving',
    same: 'Same',
    worse: 'Getting worse',
    firstSession: 'First session',
    baselineSet: 'Baseline recorded',
    noHistory: 'No reports yet',
    noHistorySub: 'Record your first walk',
    days: ['Mon','Tue','Wed','Thu','Fri','Sat','Today'],
    diSuffix: '',
    symmetryScore: 'Symmetry score',
    session: 'Session',
  }
};

export const getStrings = (lang = 'bn') => STRINGS[lang] || STRINGS.bn;
