export const STRINGS = {
  bn: {
    appName: 'নিডল',
    appSubtitle: 'KNEEDLE',
    appTagline: 'আপনার হাঁটুর যত্নে, প্রতিদিন',
    startBtn: 'শুরু করুন →',
    freeNote: 'বিনামূল্যে · ইন্টারনেট লাগবে না',
    languageLabel: 'ভাষা:',
    profileTitle: 'আপনার পরিচয়',
    profileSubtitle: 'একবার সেট করুন',
    namePlaceholder: 'আপনার নাম লিখুন',
    agePlaceholder: 'বয়স',
    whichKnee: 'কোন হাঁটুতে ব্যথা?',
    kneeLeft: 'বাম',
    kneeRight: 'ডান',
    kneeBoth: 'দুটোই',
    painLevel: 'ব্যথার মাত্রা',
    painLow: 'কম',
    painMid: 'মাঝারি',
    painHigh: 'বেশি',
    saveBtn: 'সংরক্ষণ করুন →',
    greeting: 'নমস্কার 🙏',
    todayPain: 'আজ ব্যথা কেমন?',
    recordBtn: 'হাঁটা রেকর্ড করুন',
    recordSub: '১৫ সেকেন্ড · AI বিশ্লেষণ',
    historyBtn: 'আগের রিপোর্ট দেখুন',
    historySub: 'সেশন সম্পন্ন',
    weekProgress: 'এই সপ্তাহ',
    daysLabel: 'দিন ✓',
    recordTitle: 'হাঁটা রেকর্ড করুন',
    recordSubtitle: '১৫ সেকেন্ড যথেষ্ট',
    step1: 'ফোন দেওয়ালে রাখুন, মাটি থেকে ৩ ফুট উঁচুতে',
    step2: '৩ মিটার দূরে দাঁড়িয়ে লাল বোতাম চাপুন',
    step3: 'স্বাভাবিকভাবে ফোনের দিকে হাঁটুন',
    startRecord: '● রেকর্ড শুরু করুন',
    stopRecord: '⏹ থামুন',
    cancelBtn: 'বাতিল',
    analyseBtn: 'বিশ্লেষণ করুন →',
    analysisStep1: 'পদক্ষেপের ছন্দ বিশ্লেষণ',
    analysisStep2: 'হাঁটুর কোণ পরিমাপ হচ্ছে...',
    analysisStep3: 'ভারসাম্য মূল্যায়ন',
    analysisStep4: 'রিপোর্ট তৈরি',
    rightKneeLabel: 'ডান হাঁটু',
    leftKneeLabel: 'বাম হাঁটু',
    resultsTitle: 'আজকের রিপোর্ট',
    observationTag: '🔍 যা দেখা গেল',
    fixTag: '✏️ আজ একটাই কাজ',
    exerciseTag: '🧘 আজকের ব্যায়াম',
    speakBtn: '🔊 বাংলায় শুনুন',
    saveReport: 'রিপোর্ট সংরক্ষণ করুন',
    homeBtn: 'হোমে ফিরুন',
    historyTitle: 'অগ্রগতি',
    painTrend: 'ব্যথার মাত্রা · গত ৭ দিন',
    improving: 'উন্নতি হচ্ছে',
    same: 'একই রকম',
    worse: 'খারাপ হচ্ছে',
    firstSession: 'প্রথম দিন',
    baselineSet: 'বেসলাইন তৈরি',
    noHistory: 'এখনো কোনো রিপোর্ট নেই',
    noHistorySub: 'প্রথম হাঁটা রেকর্ড করুন',
    days: ['সোম','মঙ্গল','বুধ','বৃহ','শুক্র','শনি','আজ'],
    diSuffix: ' দি',
    symmetryScore: 'সামঞ্জস্য স্কোর',
    session: 'সেশন',
    qLightLabel: 'আলো',
    qStableLabel: 'স্থির',
    qLightDark: '☀️ আলো কম — উজ্জ্বল ঘরে যান',
    qLightBright: '🌟 আলো বেশি — সরাসরি আলো এড়ান',
    qShaking: '📱 ফোন নড়ছে — দেওয়ালে রাখুন',
    errBadVideoTitle: 'ভিডিও পড়া যায়নি',
    errBadVideoBody: 'হাঁটার ছন্দ বুঝতে পারিনি। ভালো আলোয়, পুরো শরীর (মাথা থেকে পা পর্যন্ত) দেখা যায় এমনভাবে, ক্যামেরার পাশ দিয়ে কমপক্ষে ৫ সেকেন্ড হাঁটুন।',
    errTimeoutTitle: 'সময় শেষ',
    errTimeoutBody: 'সার্ভার থেকে উত্তর আসেনি। ইন্টারনেট কানেকশন দেখুন এবং আবার চেষ্টা করুন।',
    errNetworkTitle: 'সংযোগ পাচ্ছি না',
    errNetworkBody: 'সার্ভারের সাথে যোগাযোগ করা যাচ্ছে না। Wi-Fi চেক করে আবার চেষ্টা করুন।',
    errGenericTitle: 'বিশ্লেষণ ব্যর্থ হয়েছে',
    recordAgainBtn: '🎥 আবার রেকর্ড করুন',
    tryAgainBtn: '↻ আবার চেষ্টা করুন',
    goBackBtn: '← ফিরে যান',
    // F0 — dual recording
    recordStepOf: 'এর মধ্যে',
    recordFrontalTitle: 'ধাপ ১ — সামনের ভিউ',
    recordSagittalTitle: 'ধাপ ২ — পাশের ভিউ',
    recordFrontalBanner: '🚶 ক্যামেরার দিকে হাঁটুন, তারপর ফিরে যান',
    recordSagittalBanner: '🚶 ক্যামেরার পাশ দিয়ে হাঁটুন (পাশ থেকে)',
    recordFrontalDone: '✓ সামনের ভিউ ধরা হয়েছে! এখন পাশের ভিউ।',
    nextSideView: 'পরবর্তী: পাশের ভিউ →',
    step1Frontal: 'ফোন দেওয়ালে রাখুন, মাটি থেকে ৩ ফুট উঁচুতে',
    step2Frontal: '৩ মিটার দূরে দাঁড়িয়ে লাল বোতাম চাপুন',
    step3Frontal: 'ক্যামেরার দিকে ও পিছনে স্বাভাবিকভাবে হাঁটুন',
    step1Sagittal: 'ফোনের অবস্থান একই রাখুন',
    step2Sagittal: 'ক্যামেরার পাশ থেকে ৩ মিটার দূরে দাঁড়ান',
    step3Sagittal: 'পাশ দিয়ে স্বাভাবিকভাবে হাঁটুন (পাশ থেকে দেখা যাক)',
    // F1 — KL stage
    klStageLabel: 'হাঁটুর অবস্থা',
    klMild: 'হালকা',
    klModerate: 'মাঝারি',
    klSevere: 'গুরুতর',
    klStagePrefix: 'স্তর',
    klBilateralNote: 'উভয় হাঁটু আক্রান্ত',
    klTrendLabel: 'হাঁটুর অবস্থার পরিবর্তন',
    // F2 — clinical flags
    flagsFoundTitle: '🔬 বিস্তারিত বিশ্লেষণ',
    flagsFoundNone: '✓ এই সেশনে কোনো নির্দিষ্ট সমস্যা পাওয়া যায়নি',
    flagWhyLabel: 'কেন এটি গুরুত্বপূর্ণ',
    // F3 — bilateral strip
    bilatTitle: 'বাম বনাম ডান হাঁটু',
    bilatRight: 'ডান',
    bilatLeft: 'বাম',
    bilatSwingFlex: 'সুইং ফ্লেক্সন',
    bilatExtLag: 'এক্সটেনশন ল্যাগ',
    bilatLoading: 'লোডিং রেসপন্স',
    bilatRomDelta: 'ROM পরিসীমা',
    // F4 — fall risk
    fallRiskTitle: 'ভারসাম্য সতর্কতা',
    fallRiskBody: 'আপনার শরীর সতর্কতার সাথে হাঁটছে। এই সপ্তাহের পরিকল্পনায় আস্থা বাড়ানোর ব্যায়াম যোগ করা হয়েছে।',
    // F5 — gait speed
    gaitSpeedLabel: 'হাঁটার গতি',
    gaitSpeedGoal: 'লক্ষ্য: ০.৮ m/s',
    gaitSpeedGoalNote: '০.৮ m/s — স্বাধীনভাবে বাজারে যাওয়ার থ্রেশহোল্ড',
    // F6 — flag clearance
    flagProgressTitle: 'সমস্যার অগ্রগতি',
    flagCleared: '✓ সমাধান হয়েছে',
    flagNew: '● নতুন',
    flagPersisting: '→ এখনো আছে',
    flagAllClear: 'এই সেশনে কোনো সমস্যা নেই',
    flagCount: 'সমস্যা পাওয়া গেছে',
    // F9 — symptom correlation
    symptomCorrTitle: 'ব্যথা ও হাঁটার সম্পর্ক',
    symptomCorrBody: 'যখন আপনার গেইট স্কোর বেশি ছিল, সেদিনের ব্যথা গড়ে কম ছিল।',
    symptomCorrNotEnough: 'আরও সেশন রেকর্ড করুন — তারপর এখানে সংযোগ দেখা যাবে।',
    // F10 — morning check-in
    morningTitle: '🌅 সকালের চেকআপ',
    morningGo: 'চমৎকার! আজ ব্যায়াম করুন।',
    morningEasy: 'আজ হালকা করুন — জেন্টল ভার্সন চেষ্টা করুন।',
    morningRest: 'আজ বিশ্রাম নিন। ১৫ মিনিট বরফ দিন। ব্যায়াম করবেন না।',
    morningRescan: 'দিন হয়ে গেছে — একটি দ্রুত রি-স্ক্যান আপনার পরিকল্পনা আপডেট করবে।',
    // clear records
    clearAllBtn: '🗑 সব রেকর্ড মুছুন',
    clearAllConfirmTitle: 'সব রেকর্ড মুছবেন?',
    clearAllConfirmBody: 'সব সেশন ও ব্যথার লগ চিরতরে মুছে যাবে। এটি পূর্বাবস্থায় ফেরানো যাবে না।',
    clearAllConfirmOk: 'মুছুন',
    clearAllConfirmCancel: 'বাতিল',
  },

  hi: {
    appName: 'नीडल',
    appSubtitle: 'KNEEDLE',
    appTagline: 'आपके घुटनों की देखभाल, हर दिन',
    startBtn: 'शुरू करें →',
    freeNote: 'मुफ़्त · इंटरनेट की ज़रूरत नहीं',
    languageLabel: 'भाषा:',
    profileTitle: 'आपका परिचय',
    profileSubtitle: 'एक बार सेट करें',
    namePlaceholder: 'अपना नाम लिखें',
    agePlaceholder: 'उम्र',
    whichKnee: 'कौन सा घुटना दर्द करता है?',
    kneeLeft: 'बायाँ',
    kneeRight: 'दायाँ',
    kneeBoth: 'दोनों',
    painLevel: 'दर्द का स्तर',
    painLow: 'कम',
    painMid: 'मध्यम',
    painHigh: 'ज़्यादा',
    saveBtn: 'सहेजें →',
    greeting: 'नमस्ते 🙏',
    todayPain: 'आज दर्द कैसा है?',
    recordBtn: 'चलना रिकॉर्ड करें',
    recordSub: '१५ सेकंड · AI विश्लेषण',
    historyBtn: 'पुरानी रिपोर्ट देखें',
    historySub: 'सत्र पूरे हुए',
    weekProgress: 'इस हफ़्ते',
    daysLabel: 'दिन ✓',
    recordTitle: 'चलना रिकॉर्ड करें',
    recordSubtitle: '१५ सेकंड काफ़ी है',
    step1: 'फ़ोन को दीवार से लगाएं, ३ फ़ीट ऊँचाई पर',
    step2: '३ मीटर दूर खड़े होकर लाल बटन दबाएं',
    step3: 'स्वाभाविक रूप से फ़ोन की तरफ़ चलें',
    startRecord: '● रिकॉर्ड शुरू करें',
    stopRecord: '⏹ रुकें',
    cancelBtn: 'रद्द करें',
    analyseBtn: 'विश्लेषण करें →',
    analysisStep1: 'क़दमों की लय का विश्लेषण',
    analysisStep2: 'घुटने का कोण माप रहे हैं...',
    analysisStep3: 'संतुलन मूल्यांकन',
    analysisStep4: 'रिपोर्ट तैयार हो रही है',
    rightKneeLabel: 'दायाँ घुटना',
    leftKneeLabel: 'बायाँ घुटना',
    resultsTitle: 'आज की रिपोर्ट',
    observationTag: '🔍 जो दिखा',
    fixTag: '✏️ आज बस एक काम',
    exerciseTag: '🧘 आज का व्यायाम',
    speakBtn: '🔊 हिंदी में सुनें',
    saveReport: 'रिपोर्ट सहेजें',
    homeBtn: 'होम पर जाएं',
    historyTitle: 'प्रगति',
    painTrend: 'दर्द का स्तर · पिछले ७ दिन',
    improving: 'सुधार हो रहा है',
    same: 'वही स्थिति',
    worse: 'बिगड़ रहा है',
    firstSession: 'पहला दिन',
    baselineSet: 'बेसलाइन तैयार',
    noHistory: 'अभी कोई रिपोर्ट नहीं',
    noHistorySub: 'पहला चलना रिकॉर्ड करें',
    days: ['सोम','मंगल','बुध','गुरु','शुक्र','शनि','आज'],
    diSuffix: ' जी',
    symmetryScore: 'समरूपता स्कोर',
    session: 'सत्र',
    qLightLabel: 'रोशनी',
    qStableLabel: 'स्थिर',
    qLightDark: '☀️ रोशनी कम है — रोशन जगह जाएं',
    qLightBright: '🌟 बहुत तेज़ रोशनी — सीधी धूप से बचें',
    qShaking: '📱 फ़ोन हिल रहा है — दीवार से लगाएं',
    errBadVideoTitle: 'वीडियो पढ़ नहीं सके',
    errBadVideoBody: 'चलने का तरीक़ा समझ नहीं आया। अच्छी रोशनी में, पूरा शरीर (सिर से पैर तक) दिखाई दे, कैमरे के बग़ल से कम से कम ५ सेकंड चलें।',
    errTimeoutTitle: 'समय समाप्त',
    errTimeoutBody: 'सर्वर से जवाब नहीं आया। इंटरनेट कनेक्शन देखें और फिर कोशिश करें।',
    errNetworkTitle: 'कनेक्शन नहीं मिला',
    errNetworkBody: 'सर्वर से संपर्क नहीं हो पा रहा। Wi-Fi जाँचकर फिर कोशिश करें।',
    errGenericTitle: 'विश्लेषण विफल',
    recordAgainBtn: '🎥 दोबारा रिकॉर्ड करें',
    tryAgainBtn: '↻ फिर कोशिश करें',
    goBackBtn: '← वापस जाएं',
    // F0 — dual recording
    recordStepOf: 'में से',
    recordFrontalTitle: 'चरण १ — सामने का दृश्य',
    recordSagittalTitle: 'चरण २ — बगल का दृश्य',
    recordFrontalBanner: '🚶 कैमरे की तरफ़ चलें, फिर वापस आएं',
    recordSagittalBanner: '🚶 कैमरे के बगल से चलें (साइड व्यू)',
    recordFrontalDone: '✓ सामने का दृश्य लिया गया! अब बगल का।',
    nextSideView: 'अगला: बगल का दृश्य →',
    step1Frontal: 'फ़ोन को दीवार से लगाएं, ३ फ़ीट ऊँचाई पर',
    step2Frontal: '३ मीटर दूर खड़े होकर लाल बटन दबाएं',
    step3Frontal: 'कैमरे की तरफ़ और वापस स्वाभाविक रूप से चलें',
    step1Sagittal: 'फ़ोन की जगह वही रखें',
    step2Sagittal: 'कैमरे के बगल में ३ मीटर दूर खड़े हों',
    step3Sagittal: 'बगल से स्वाभाविक रूप से चलें (साइड दिखे)',
    // F1 — KL stage
    klStageLabel: 'घुटने की स्थिति',
    klMild: 'हल्का',
    klModerate: 'मध्यम',
    klSevere: 'गंभीर',
    klStagePrefix: 'स्तर',
    klBilateralNote: 'दोनों घुटने प्रभावित',
    klTrendLabel: 'घुटने की स्थिति में बदलाव',
    // F2 — clinical flags
    flagsFoundTitle: '🔬 विस्तृत विश्लेषण',
    flagsFoundNone: '✓ इस सत्र में कोई विशेष समस्या नहीं मिली',
    flagWhyLabel: 'यह क्यों ज़रूरी है',
    // F3 — bilateral strip
    bilatTitle: 'बायाँ बनाम दायाँ घुटना',
    bilatRight: 'दायाँ',
    bilatLeft: 'बायाँ',
    bilatSwingFlex: 'स्विंग फ्लेक्सन',
    bilatExtLag: 'एक्सटेंशन लैग',
    bilatLoading: 'लोडिंग रिस्पॉन्स',
    bilatRomDelta: 'ROM रेंज',
    // F4 — fall risk
    fallRiskTitle: 'संतुलन सावधानी',
    fallRiskBody: 'आपका शरीर सावधानी से चल रहा है। इस हफ्ते की योजना में आत्मविश्वास बढ़ाने के व्यायाम जोड़े गए हैं।',
    // F5 — gait speed
    gaitSpeedLabel: 'चलने की गति',
    gaitSpeedGoal: 'लक्ष्य: ०.८ m/s',
    gaitSpeedGoalNote: '०.८ m/s — स्वतंत्र रूप से बाज़ार जाने की सीमा',
    // F6 — flag clearance
    flagProgressTitle: 'समस्या प्रगति',
    flagCleared: '✓ हल हुआ',
    flagNew: '● नया',
    flagPersisting: '→ अभी भी है',
    flagAllClear: 'इस सत्र में कोई समस्या नहीं',
    flagCount: 'समस्याएँ मिलीं',
    // F9 — symptom correlation
    symptomCorrTitle: 'दर्द और चाल का संबंध',
    symptomCorrBody: 'जब गेट स्कोर अधिक था, उस दिन दर्द औसतन कम था।',
    symptomCorrNotEnough: 'और सत्र रिकॉर्ड करें — तब यहाँ संबंध दिखेगा।',
    // F10 — morning check-in
    morningTitle: '🌅 सुबह की जाँच',
    morningGo: 'बढ़िया! आज व्यायाम करें।',
    morningEasy: 'आज हल्का करें — जेंटल वर्ज़न आज़माएं।',
    morningRest: 'आज आराम करें। १५ मिनट बर्फ लगाएं। व्यायाम न करें।',
    morningRescan: 'दिन हो गए — एक त्वरित री-स्कैन आपकी योजना अपडेट करेगा।',
    // clear records
    clearAllBtn: '🗑 सभी रिकॉर्ड हटाएं',
    clearAllConfirmTitle: 'सभी रिकॉर्ड हटाएं?',
    clearAllConfirmBody: 'सभी सत्र और दर्द का लॉग हमेशा के लिए हट जाएगा। यह पूर्ववत नहीं किया जा सकता।',
    clearAllConfirmOk: 'हटाएं',
    clearAllConfirmCancel: 'रद्द करें',
  },

  en: {
    appName: 'Kneedle',
    appSubtitle: 'KNEEDLE',
    appTagline: 'Your personal knee physiotherapist',
    startBtn: 'Get Started →',
    freeNote: 'Free · No internet needed',
    languageLabel: 'Language:',
    profileTitle: 'Your Profile',
    profileSubtitle: 'Set once, remembered always',
    namePlaceholder: 'Your name',
    agePlaceholder: 'Age',
    whichKnee: 'Which knee hurts?',
    kneeLeft: 'Left',
    kneeRight: 'Right',
    kneeBoth: 'Both',
    painLevel: 'Pain level',
    painLow: 'Low',
    painMid: 'Medium',
    painHigh: 'High',
    saveBtn: 'Save →',
    greeting: 'Hello 🙏',
    todayPain: 'How is the pain today?',
    recordBtn: 'Record your walk',
    recordSub: '15 seconds · AI analysis',
    historyBtn: 'View past reports',
    historySub: 'sessions done',
    weekProgress: 'This week',
    daysLabel: 'days ✓',
    recordTitle: 'Record your walk',
    recordSubtitle: '8 seconds is enough',
    step1: 'Lean phone against wall, 3 feet off ground',
    step2: 'Stand 3 metres away, press red button',
    step3: 'Walk naturally toward the phone',
    startRecord: '● Start Recording',
    stopRecord: '⏹ Stop',
    cancelBtn: 'Cancel',
    analyseBtn: 'Analyse →',
    analysisStep1: 'Analysing step rhythm',
    analysisStep2: 'Measuring knee angle...',
    analysisStep3: 'Balance assessment',
    analysisStep4: 'Generating report',
    rightKneeLabel: 'Right knee',
    leftKneeLabel: 'Left knee',
    resultsTitle: "Today's Report",
    observationTag: '🔍 What we observed',
    fixTag: '✏️ One thing to do today',
    exerciseTag: "🧘 Today's exercises",
    speakBtn: '🔊 Read aloud',
    saveReport: 'Save report',
    homeBtn: 'Back to home',
    historyTitle: 'Progress',
    painTrend: 'Pain level · Last 7 days',
    improving: 'Improving',
    same: 'Same',
    worse: 'Getting worse',
    firstSession: 'First session',
    baselineSet: 'Baseline recorded',
    noHistory: 'No reports yet',
    noHistorySub: 'Record your first walk',
    days: ['Mon','Tue','Wed','Thu','Fri','Sat','Today'],
    diSuffix: '',
    symmetryScore: 'Symmetry score',
    session: 'Session',
    qLightLabel: 'Light',
    qStableLabel: 'Steady',
    qLightDark: '☀️ Too dark — move to a brighter area',
    qLightBright: '🌟 Too bright — avoid direct sunlight',
    qShaking: '📱 Phone moving — lean it against a wall',
    errBadVideoTitle: "Couldn't read the video",
    errBadVideoBody: "We couldn't read your walking pattern from this video. Please record again in good lighting, with your full body visible from head to toe, walking sideways to the camera for at least 5 seconds.",
    errTimeoutTitle: 'Timed out',
    errTimeoutBody: 'The server did not respond in time. Check your connection and try again.',
    errNetworkTitle: 'Cannot reach server',
    errNetworkBody: "Couldn't reach the analysis server. Check your Wi-Fi and try again.",
    errGenericTitle: 'Analysis failed',
    recordAgainBtn: '🎥 Record again',
    tryAgainBtn: '↻ Try again',
    goBackBtn: '← Go back',
    // F0 — dual recording
    recordStepOf: 'of',
    recordFrontalTitle: 'Step 1 — Frontal View',
    recordSagittalTitle: 'Step 2 — Side View',
    recordFrontalBanner: '🚶 Walk toward the camera, then back',
    recordSagittalBanner: '🚶 Walk sideways across the frame',
    recordFrontalDone: '✓ Front view captured! Now the side view.',
    nextSideView: 'Next: Side View →',
    step1Frontal: 'Lean phone against wall, 3 feet off ground',
    step2Frontal: 'Stand 3 metres away, press red button',
    step3Frontal: 'Walk toward the camera and back naturally',
    step1Sagittal: 'Keep phone in the same position',
    step2Sagittal: 'Stand 3 metres to the side of the camera',
    step3Sagittal: 'Walk sideways across the frame naturally',
    // F1 — KL stage
    klStageLabel: 'Knee Stage',
    klMild: 'Mild',
    klModerate: 'Moderate',
    klSevere: 'Severe',
    klStagePrefix: 'Stage',
    klBilateralNote: 'Both knees affected',
    klTrendLabel: 'Knee Stage Over Time',
    // F2 — clinical flags
    flagsFoundTitle: '🔬 Detailed Findings',
    flagsFoundNone: '✓ No specific issues detected this session',
    flagWhyLabel: 'Why this matters',
    // F3 — bilateral strip
    bilatTitle: 'Left vs Right Knee',
    bilatRight: 'Right',
    bilatLeft: 'Left',
    bilatSwingFlex: 'Swing flexion',
    bilatExtLag: 'Extension lag',
    bilatLoading: 'Loading response',
    bilatRomDelta: 'ROM range',
    // F4 — fall risk
    fallRiskTitle: 'Balance Check',
    fallRiskBody: "Your body is walking cautiously. This week's plan includes confidence-building balance exercises.",
    // F5 — gait speed
    gaitSpeedLabel: 'Walking Speed',
    gaitSpeedGoal: 'Goal: 0.8 m/s',
    gaitSpeedGoalNote: '0.8 m/s — threshold for walking to market independently',
    // F6 — flag clearance
    flagProgressTitle: 'Issue Tracker',
    flagCleared: '✓ Resolved',
    flagNew: '● New',
    flagPersisting: '→ Still present',
    flagAllClear: 'No issues this session',
    flagCount: 'issues found',
    // F9 — symptom correlation
    symptomCorrTitle: 'Pain & Gait Link',
    symptomCorrBody: 'When your gait score was higher, morning pain tended to be lower.',
    symptomCorrNotEnough: 'Record more sessions — the pain-gait connection will appear here.',
    // F10 — morning check-in
    morningTitle: '🌅 Morning Check-in',
    morningGo: 'Good to go! Do your exercises today.',
    morningEasy: 'Take it easy — try the gentle version today.',
    morningRest: 'Rest today. Ice for 15 minutes. Skip exercises.',
    morningRescan: "days since your last scan — a quick re-scan will update your plan.",
    // clear records
    clearAllBtn: '🗑 Delete all records',
    clearAllConfirmTitle: 'Delete all records?',
    clearAllConfirmBody: 'All sessions and pain logs will be permanently erased. This cannot be undone.',
    clearAllConfirmOk: 'Delete',
    clearAllConfirmCancel: 'Cancel',
  }
};

export const getStrings = (lang = 'bn') => STRINGS[lang] || STRINGS.bn;
